import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Share_Tech_Mono } from "next/font/google";
import { Oxanium } from "next/font/google";
import Footer from "../components/Footer";
import { ToastProvider } from "./hooks/useToast";
import localFont from "next/font/local";

const echocore = localFont({
  src: [
    {
      path: "../../public/fonts/titleFont.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-echocore",
})

const shareTechMono = Share_Tech_Mono({
  variable: "--font-share-tech-mono",
  weight: "400",
  subsets: ["latin"],
})

const oxanium = Oxanium({
  variable: "--font-oxanium",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <link rel="stylesheet" type='text/css' href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" precedence="default"/>
      <body
        className={`${shareTechMono.variable} ${oxanium.variable} ${echocore.variable} antialiased`}
      >
        <Navbar/>
        <ToastProvider>
        {children}
        </ToastProvider>
        <Footer/>
      </body>
    </html>
  );
}
